language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

# safelist
branches:
  only:
  - master
  - develop

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn install --no-progress
  - yarn lint
  - yarn build --prod --base-href https://jnrndn.github.io/pwa-push-notifications/ --no-progress
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-pwa-push-notifications
  on:
    branch: master